In [13]:
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

In [18]:
np.random.seed(42)
data=np.random.rand(100,2)
data

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258],
       [0.02058449, 0.96990985],
       [0.83244264, 0.21233911],
       [0.18182497, 0.18340451],
       [0.30424224, 0.52475643],
       [0.43194502, 0.29122914],
       [0.61185289, 0.13949386],
       [0.29214465, 0.36636184],
       [0.45606998, 0.78517596],
       [0.19967378, 0.51423444],
       [0.59241457, 0.04645041],
       [0.60754485, 0.17052412],
       [0.06505159, 0.94888554],
       [0.96563203, 0.80839735],
       [0.30461377, 0.09767211],
       [0.68423303, 0.44015249],
       [0.12203823, 0.49517691],
       [0.03438852, 0.9093204 ],
       [0.25877998, 0.66252228],
       [0.31171108, 0.52006802],
       [0.54671028, 0.18485446],
       [0.96958463, 0.77513282],
       [0.93949894, 0.89482735],
       [0.59789998, 0.92187424],
       [0.0884925 , 0.19598286],
       [0.04522729, 0.32533033],
       [0.

In [15]:
cntr,u,u0,d,jm,p,fpc=fuzz.cluster.cmeans(data.T,3,2,error=0.005,maxiter=1000,init=None)

In [16]:
clus_center=cntr.T
print("Cluster Centers:")
print(clus_center)

Cluster Centers:
[[0.40570255 0.17838805 0.79775305]
 [0.20560217 0.71920952 0.61194876]]


In [17]:
cluster_membership=u
print("Cluster Membership:")
print(cluster_membership)

Cluster Membership:
[[0.1119421  0.01672453 0.7642125  0.05761203 0.11503851 0.09664067
  0.41698334 0.78976968 0.28272792 0.93782173 0.78661493 0.71201347
  0.13403129 0.21656979 0.79192218 0.78854357 0.08183828 0.08186619
  0.91121147 0.2210228  0.22580771 0.07648761 0.0390733  0.30157578
  0.88417695 0.07429721 0.10165942 0.13196241 0.66387529 0.48612494
  0.96607126 0.22635765 0.21855497 0.01876193 0.09241945 0.50009775
  0.06499032 0.05289124 0.58239678 0.95296221 0.01123416 0.90369965
  0.82812004 0.01756215 0.07973202 0.01010578 0.01517537 0.06139841
  0.53098316 0.63716244 0.07692137 0.33301657 0.32208825 0.12110448
  0.83772347 0.92504192 0.07395618 0.1190566  0.47339577 0.03835037
  0.09624942 0.92767631 0.46647044 0.08323849 0.20586495 0.99728081
  0.54039673 0.23237045 0.15968552 0.11294946 0.29722829 0.8647332
  0.85995    0.23261584 0.55001708 0.33176367 0.24431576 0.29888733
  0.07997324 0.01165088 0.16085865 0.15200906 0.03959621 0.95834605
  0.10586564 0.69214612 0.922